package com.aquagrid.platform.iot.domain.model;

/**
 * Where a device's telemetry comes from.
 *
 * <p>Deliberately not a {@link CommunicationProfile}. A communication profile names the network a
 * device speaks on and declares what must be provisioned to address it there; this names whether
 * the traffic arriving on that network is real. They vary independently: a simulated meter emulates
 * NB-IoT or LoRaWAN complete with an IMEI or DevEUI, and a live meter is live whichever radio it
 * carries.
 *
 * <p>Conflating them — as {@code CommunicationProfile.SIMULATOR} once did — costs more than tidiness.
 * A profile has to declare an identity field for a device to receive an address, and "simulator" has
 * no such field to declare, so every device registered that way was unresolvable by the ingest path.
 * Modelling the distinction as its own axis lets a simulated device be addressed exactly like the
 * device it stands in for.
 */
public enum DeviceSource {

    /** A real device in the field. Its readings are measurements. */
    LIVE,

    /**
     * Synthetic traffic generated by the platform's fleet simulator (Module 17).
     *
     * <p>Carried on the device row rather than inferred from the reading tag so that a device can be
     * excluded from a water balance or an NRW figure without first querying its telemetry — and so
     * that the exclusion survives the device going quiet.
     */
    SIMULATOR,

    /**
     * Traffic injected by an operator from Postman or another HTTP/MQTT client during integration
     * testing — neither a field device nor the fleet simulator.
     *
     * <p>Kept distinct from {@link #LIVE} so a water balance can exclude it, and from
     * {@link #SIMULATOR} so the fleet driver does not claim devices an engineer is hand-posting
     * against.
     */
    API_TEST;

    /** Resolves a source string from the API or the database; null when it names no source. */
    public static DeviceSource from(String value) {
        if (value == null) {
            return null;
        }
        for (DeviceSource source : values()) {
            if (source.name().equalsIgnoreCase(value.trim())) {
                return source;
            }
        }
        return null;
    }
}
