-- =====================================================================================
-- Module 4 — GIS dashboard and spatial assets
-- Owner : module-gis (version range V1300–V1399)
--
-- The `gis.assets` supertype carries everything common to every spatial asset: tenant,
-- asset code, status, install date, geometry (EPSG:4326) and a generated Web-Mercator
-- geometry (EPSG:3857) for cheap tile serving. Type tables (pipelines, valves, tanks…)
-- hold the type-specific columns and reference this supertype.
--
-- Design decisions (locked in Phase 0, see docs/04-database-design.md §4.4):
--  * geometry(Point/MultiPolygon/..., 4326) + GiST index for spatial predicates.
--  * a GENERATED geom_3857 column: ST_AsMVT operates in Web Mercator, and reprojecting per
--    tile request is the dominant cost at scale. Materialising it once on write is the fix.
--  * attributes jsonb + GIN index for utility-specific fields that must not require a
--    migration per customer (contract numbers, ward codes, manufacturer data).
-- =====================================================================================

-- ---- Enumerations as CHECK-constrained VARCHAR ----------------------------------------
-- Not PG ENUM types: ENUM requires ALTER TYPE and an exclusive lock, and ordinals break on
-- reorder. VARCHAR + CHECK is cheap and migration-safe.

CREATE TABLE gis.assets
(
    id              UUID PRIMARY KEY                  DEFAULT gen_random_uuid(),
    organization_id UUID         NOT NULL,
    asset_code      VARCHAR(80)  NOT NULL,
    asset_type      VARCHAR(40)  NOT NULL,
    name            VARCHAR(200) NOT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'IN_SERVICE',
    install_date     DATE,
    decommission_date DATE,

    -- Authoritative geometry in EPSG:4326 (lon/lat). All edits happen against this column.
    geom            geometry NOT NULL,

    -- Web-Mercator reprojection, generated by the database on insert/update. ST_AsMVT reads
    -- this; avoiding a per-tile ST_Transform is what makes vector tiles cheap at scale.
    geom_3857       geometry GENERATED ALWAYS AS (ST_Transform(geom, 3857)) STORED,

    -- Utility-specific extensions without a migration per customer.
    attributes      JSONB        NOT NULL DEFAULT '{}'::jsonb,

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      UUID,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by      UUID,
    version         BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT fk_assets_organization
        FOREIGN KEY (organization_id) REFERENCES core.organizations (id) ON DELETE RESTRICT,
    CONSTRAINT ck_assets_type CHECK (asset_type IN
        ('METER', 'VALVE', 'PIPELINE', 'HYDRANT', 'TANK', 'RESERVOIR',
         'PUMP_STATION', 'DMA', 'SERVICE_CONNECTION', 'SENSOR')),
    CONSTRAINT ck_assets_status CHECK (status IN
        ('PLANNED', 'IN_SERVICE', 'OUT_OF_SERVICE', 'DECOMMISSIONED', 'DAMAGED'))
);

-- Tenant + code uniqueness: an asset code is meaningful only within a tenant.
CREATE UNIQUE INDEX uq_assets_org_code ON gis.assets (organization_id, asset_code);
CREATE INDEX ix_assets_org_type ON gis.assets (organization_id, asset_type);
CREATE INDEX ix_assets_org_status ON gis.assets (organization_id, status);

-- Spatial indexes on BOTH SRIDs: 4326 for ST_Intersects/ST_DWithin analytical queries,
-- 3857 for tile-bbox clipping in ST_AsMVT. Both are GiST.
CREATE INDEX ix_assets_geom_4326 ON gis.assets USING GIST (geom);
CREATE INDEX ix_assets_geom_3857 ON gis.assets USING GIST (geom_3857);

-- Attribute bag search: GIN supports the @> containment operator and jsonb_path_query.
CREATE INDEX ix_assets_attributes ON gis.assets USING GIN (attributes);

CREATE TRIGGER trg_assets_updated_at
    BEFORE UPDATE ON gis.assets
    FOR EACH ROW EXECUTE FUNCTION core.set_updated_at();

COMMENT ON TABLE gis.assets IS
    'Spatial asset supertype. Type-specific tables reference this by id.';
COMMENT ON COLUMN gis.assets.geom IS
    'Authoritative geometry, EPSG:4326. Analytical distance/length uses geography() or an explicit UTM transform.';
COMMENT ON COLUMN gis.assets.geom_3857 IS
    'Generated Web-Mercator geometry for vector-tile serving. Never edited directly.';

-- ---- Layer catalogue -------------------------------------------------------------------
-- Describes the named layers the map renders. Drives the layer tree in the UI and the
-- /gis/layers endpoint. A layer maps to an asset_type (or, later, a custom query).
CREATE TABLE gis.layers
(
    id              UUID PRIMARY KEY                  DEFAULT gen_random_uuid(),
    organization_id UUID         NOT NULL,
    code            VARCHAR(60)  NOT NULL,        -- e.g. 'meters', 'valves', 'pipelines'
    title           VARCHAR(120) NOT NULL,
    asset_type      VARCHAR(40)  NOT NULL,
    is_visible      BOOLEAN      NOT NULL DEFAULT TRUE,
    sort_order      INTEGER      NOT NULL DEFAULT 0,
    style           JSONB        NOT NULL DEFAULT '{}'::jsonb,  -- future: SLD/MapLibre style blob
    -- Layer extends AuditableEntity, so it carries the same audit and optimistic-locking
    -- columns as gis.assets. Omitting them makes the entity unmappable.
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      UUID,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by      UUID,
    version         BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT fk_layers_organization
        FOREIGN KEY (organization_id) REFERENCES core.organizations (id) ON DELETE CASCADE,
    CONSTRAINT ck_layers_asset_type CHECK (asset_type IN
        ('METER', 'VALVE', 'PIPELINE', 'HYDRANT', 'TANK', 'RESERVOIR',
         'PUMP_STATION', 'DMA', 'SERVICE_CONNECTION', 'SENSOR'))
);

CREATE UNIQUE INDEX uq_layers_org_code ON gis.layers (organization_id, code);
CREATE INDEX ix_layers_org_order ON gis.layers (organization_id, sort_order);

CREATE TRIGGER trg_layers_updated_at
    BEFORE UPDATE ON gis.layers
    FOR EACH ROW EXECUTE FUNCTION core.set_updated_at();

-- ---- Seed the default layer set for every existing tenant ------------------------------
-- A utility opening the map for the first time should see a sensible layer tree, not an
-- empty map. Meters, valves, pipelines and hydrants are the everyday operational layers.
INSERT INTO gis.layers (organization_id, code, title, asset_type, is_visible, sort_order)
SELECT o.id, l.code, l.title, l.asset_type::varchar, l.is_visible, l.sort_order
FROM core.organizations o
CROSS JOIN (VALUES
    ('meters',    'Meters',         'METER',     TRUE,  10),
    ('valves',    'Valves',         'VALVE',     TRUE,  20),
    ('pipelines', 'Pipelines',      'PIPELINE',  TRUE,  30),
    ('hydrants',  'Hydrants',       'HYDRANT',   TRUE,  40),
    ('tanks',     'Tanks',          'TANK',      FALSE, 50),
    ('reservoirs','Reservoirs',     'RESERVOIR', FALSE, 60),
    ('pumps',     'Pump Stations',  'PUMP_STATION', FALSE, 70),
    ('dmas',      'DMAs',           'DMA',       FALSE, 80)
) AS l(code, title, asset_type, is_visible, sort_order);
