import { Box, Card, Chip, Divider, Stack, Tooltip, Typography } from '@mui/material';
import type { DeviceTelemetry } from '../types';
import { formatAge } from '../labels';
import { formatTimestamp } from '@/features/receiver/labels';
import { DeviceStatusChip } from '@/features/devices/components/DeviceStatusChip';
import type { DeviceStatus } from '@/features/devices/types';

/**
 * What this device *is*, beside what it is reading.
 *
 * Both, on one screen, deliberately. A flow rate means one thing at a household connection and
 * another at a reservoir outlet, so an operator judging a reading needs the device's identity and
 * siting in front of them — and holding the device register open in a second tab to get it is how
 * the wrong meter gets investigated.
 */
export function DeviceInfoPanel({ device }: { device: DeviceTelemetry }) {
  return (
    <Card variant="outlined">
      <Box sx={{ px: 2, py: 1.5 }}>
        <Stack direction="row" spacing={1} alignItems="center" flexWrap="wrap" useFlexGap>
          <Typography variant="subtitle1" noWrap>
            {device.deviceCode}
          </Typography>
          {device.status ? <DeviceStatusChip status={device.status as DeviceStatus} /> : null}
          {/* Only the exception is badged. A "Live" chip on every device is noise that trains the
              eye to skip exactly the flag it exists to show. */}
          {device.deviceSource === 'SIMULATOR' ? (
            <Tooltip title="Readings are generated by the fleet simulator, not measured by a device in the ground.">
              <Chip size="small" color="info" variant="outlined" label="Simulated" />
            </Tooltip>
          ) : null}
        </Stack>
        <Typography variant="body2" color="text.secondary">
          {device.name}
        </Typography>
      </Box>
      <Divider />

      <Box sx={{ px: 2, py: 1.5 }}>
        <Stack spacing={1.25}>
          {/*
            Last heard is first and on its own, because it qualifies everything else on the screen.
            Every reading below is only as current as this.
          */}
          <Tooltip title={formatTimestamp(device.lastSeenAt)}>
            <Box>
              <Typography variant="caption" color="text.secondary" display="block">
                Last heard
              </Typography>
              <Typography variant="body2" fontWeight={600}>
                {device.lastSeenAt ? formatAge(device.silentForSeconds) : 'never'}
              </Typography>
            </Box>
          </Tooltip>

          <Divider flexItem />

          <Field label="Type" value={device.deviceType} />
          <Field label="Network" value={device.transport} />
          <Field label="Address" value={device.networkAddress} mono />
          <Field label="Asset" value={device.assetNumber} />
          <Field label="Manufacturer" value={device.manufacturer} />
          <Field label="Model" value={device.model} />
          <Field label="Serial" value={device.serialNumber} mono />
          <Field label="Firmware" value={device.firmwareVersion} />
          <Field
            label="Installed"
            value={device.installationDate ? device.installationDate.slice(0, 10) : undefined}
          />
          <Field
            label="Position"
            value={
              device.latitude !== undefined && device.longitude !== undefined
                ? `${device.latitude.toFixed(5)}, ${device.longitude.toFixed(5)}`
                : undefined
            }
            mono
          />
        </Stack>
      </Box>
    </Card>
  );
}

// `string | undefined` spelled out rather than `value?: string`: the project runs
// exactOptionalPropertyTypes, under which an optional prop may be *omitted* but not passed as
// undefined — and every caller here passes a field that is legitimately absent.
function Field({
  label,
  value,
  mono,
}: {
  label: string;
  value: string | undefined;
  mono?: boolean;
}) {
  return (
    <Stack direction="row" justifyContent="space-between" spacing={2} alignItems="baseline">
      <Typography variant="caption" color="text.secondary" noWrap>
        {label}
      </Typography>
      <Typography
        variant="body2"
        noWrap
        fontFamily={mono ? 'monospace' : undefined}
        sx={{ textAlign: 'right', minWidth: 0 }}
      >
        {value ?? '—'}
      </Typography>
    </Stack>
  );
}
