-- =====================================================================================
-- Module 6 — Device Source, separated from the communication technology
-- Owner : module-iot (version range V1400–V1499)
--
-- V1400 listed SIMULATOR alongside LORAWAN, NB_IOT, CELLULAR, ETHERNET and HTTP in
-- `transport`, which put a category error in the schema: those five name a *network*, and
-- SIMULATOR names *where the telemetry comes from*. The two are independent — a simulated
-- device emulates a real network, and asking "is this data real?" is not the same question as
-- "which radio carries it?".
--
-- The consequence was not cosmetic. CommunicationProfile.SIMULATOR declared no identity field,
-- so a device registered as SIMULATOR got a NULL `network_address` — and ingestion resolves
-- every uplink through exactly that column. A simulator-transport device could never be bound
-- to a reading. It registered cleanly and was unreachable by construction.
--
-- This migration splits the two ideas:
--
--   * `transport` — the network the device speaks on. SIMULATOR is removed from its domain.
--   * `source`    — how the device's telemetry originates:
--                     LIVE      a real device in the field,
--                     SIMULATOR synthetic traffic generated by the platform (Module 17).
--
-- Existing SIMULATOR rows become source = 'SIMULATOR' on transport = 'HTTP'. HTTP is the
-- honest landing place: like the old SIMULATOR profile it defines no provisioning fields and no
-- network address, so the rewrite changes no device's reachability — it only stops the row from
-- claiming a radio it never had.
-- =====================================================================================

ALTER TABLE iot.devices
    -- DEFAULT 'LIVE' rather than a nullable column: "we don't know if this data is real" is not a
    -- state the fleet map or the water balance can render, and every row that exists today is a
    -- device someone registered as real.
    ADD COLUMN source VARCHAR(16) NOT NULL DEFAULT 'LIVE';

-- Backfill before the constraints, or the transport CHECK below rejects the rows it is meant to
-- migrate.
UPDATE iot.devices
SET source    = 'SIMULATOR',
    transport = 'HTTP'
WHERE transport = 'SIMULATOR';

ALTER TABLE iot.devices DROP CONSTRAINT ck_devices_transport;
ALTER TABLE iot.devices
    ADD CONSTRAINT ck_devices_transport CHECK (transport IN
        ('LORAWAN', 'NB_IOT', 'CELLULAR', 'ETHERNET', 'HTTP')),
    ADD CONSTRAINT ck_devices_source CHECK (source IN ('LIVE', 'SIMULATOR'));

-- "Show me only real devices" is the filter every operational report needs before it can be
-- trusted, and the one the device list defaults to offering.
CREATE INDEX ix_devices_org_source ON iot.devices (organization_id, source);

COMMENT ON COLUMN iot.devices.source IS
    'Where this device''s telemetry originates: LIVE (a real device in the field) or SIMULATOR (synthetic traffic from Module 17). Independent of transport, which names the network.';
COMMENT ON COLUMN iot.devices.transport IS
    'The network technology the device communicates over. Names a radio or wire only — see source for whether the traffic is real.';
